// 地区映射：国家 & 省份（可扩展）
// 该文件用于将 API 返回的英文/代码名称映射为中文展示名。

export const COUNTRY_MAP: Record<string, string> = {
  CN: '中国',
  JP: '日本',
  US: '美国',
  DE: '德国',
  FR: '法国',
  GB: '英国',
  RU: '俄罗斯',
  IN: '印度',
  BR: '巴西',
  SG: '新加坡',
  TW: '中国台湾',
  AR: '阿根廷',
  TR: '土耳其',
  KR: '韩国',
  CA: '加拿大',
  AU: '澳大利亚',
  UA: '乌克兰',
}

export const PROVINCE_MAP: Record<string, string> = {
  Beijing: "北京市",
  Tianjin: "天津市",
  Hebei: "河北省",
  Shanxi: "山西省",
  "Inner Mongolia": "内蒙古自治区",
  Liaoning: "辽宁省",
  Jilin: "吉林省",
  Heilongjiang: "黑龙江省",
  Shanghai: "上海市",
  Jiangsu: "江苏省",
  Zhejiang: "浙江省",
  Anhui: "安徽省",
  Fujian: "福建省",
  Jiangxi: "江西省",
  Shandong: "山东省",
  Henan: "河南省",
  Hubei: "湖北省",
  Hunan: "湖南省",
  Guangdong: "广东省",
  "Guangdong Province": "广东省",
  Guangxi: "广西壮族自治区",
  Hainan: "海南省",
  Chongqing: "重庆市",
  Sichuan: "四川省",
  Guizhou: "贵州省",
  Yunnan: "云南省",
  Tibet: "西藏自治区",
  Shaanxi: "陕西省",
  Gansu: "甘肃省",
  Qinghai: "青海省",
  Ningxia: "宁夏回族自治区",
  Xinjiang: "新疆维吾尔自治区",
  Taiwan: "台湾省",
  "Hong Kong": "香港特别行政区",
  Macau: "澳门特别行政区",
}
